title: Caleb Johnson # your name (or website title) here
logo: "/images/IMG_9633.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  
  <a href="https://www.linkedin.com/in/caleb-johnson-67832b2b6/">LinkedIn</a> 
  <br>
  <a href="https://docs.google.com/document/d/1G8zHBM0DJwcTOo8TThG424_lDa8U2wPs/edit?usp=sharing&ouid=107913385873671802699&rtpof=true&sd=true">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/caj224/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
